# Generated by Django 5.0.1 on 2024-01-16 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_tbl_fueltype'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_transmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transmission_name', models.CharField(max_length=50)),
            ],
        ),
    ]
