# Generated by Django 5.0.1 on 2024-01-17 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_tbl_manufacturer'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_make',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make_name', models.CharField(max_length=30)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_manufacturer')),
            ],
        ),
    ]
