# Generated by Django 5.0.1 on 2024-01-18 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_tbl_year_tbl_car'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_car',
        ),
    ]
