# Generated by Django 4.2.7 on 2024-01-18 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_tbl_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_image', models.FileField(upload_to='CarGallery/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_car')),
            ],
        ),
    ]
