# Generated by Django 4.2.7 on 2024-01-24 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_tbl_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_car',
            name='car_price',
            field=models.IntegerField(max_length=50),
        ),
    ]
