# Generated by Django 5.0.1 on 2024-02-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_alter_tbl_car_car_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_state',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=20)),
            ],
        ),
    ]
