# Generated by Django 4.2.7 on 2024-03-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0016_tbl_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_servicetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=50)),
            ],
        ),
    ]
