# Generated by Django 4.2.7 on 2024-01-20 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_tbl_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_review',
        ),
    ]
