# Generated by Django 4.2.7 on 2024-01-24 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_tbl_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_review',
        ),
    ]
