# Generated by Django 4.2.7 on 2024-03-08 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0017_tbl_servicetype'),
        ('UserApp', '0007_tbl_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_servicerquest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srequest_details', models.CharField(max_length=100)),
                ('srequest_status', models.CharField(default=0, max_length=10)),
                ('srequest_fordate', models.DateField()),
                ('srequest_date', models.DateField(auto_now_add=True)),
                ('servicetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_servicetype')),
            ],
        ),
    ]
