# Generated by Django 4.2.7 on 2024-03-08 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0002_tbl_sevicecenter'),
        ('UserApp', '0008_tbl_servicerquest'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_servicerquest',
            name='scenter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_sevicecenter'),
        ),
        migrations.AddField(
            model_name='tbl_servicerquest',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user'),
        ),
    ]
