# Generated by Django 4.2.7 on 2024-03-07 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0016_tbl_place'),
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_sevicecenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenter_name', models.CharField(max_length=30)),
                ('scenter_email', models.CharField(max_length=50)),
                ('scenter_address', models.CharField(max_length=100)),
                ('scenter_contact', models.CharField(max_length=50)),
                ('scenter_photo', models.FileField(upload_to='ScenterDocs/')),
                ('scenter_proof', models.FileField(upload_to='ScenterDocs/')),
                ('scenter_password', models.CharField(max_length=30)),
                ('scenter_vstatus', models.CharField(default=0, max_length=10)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
