# Generated by Django 5.0.1 on 2024-03-20 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0017_tbl_servicetype'),
        ('Guest', '0002_tbl_sevicecenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_sevicecenter',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_manufacturer'),
        ),
    ]
